// Generated by https://quicktype.io

class Movies {
  List<Movie> items = new List();

  Movies();

  Movies.fromJsonList(List<dynamic> jsonList) {
    if (jsonList == null) return;

    for (var item in jsonList) {
      final movie = new Movie.fromJsonMap(item);

      items.add(movie);
    }
  }
}

class Movie {
  int voteCount;
  int id;
  bool video;
  double voteAverage;
  String title;
  double popularity;
  String posterPath;
  String originalLanguage;
  String originalTitle;
  List<int> genreIds;
  String backdropPath;
  bool adult;
  String overview;
  String releaseDate;

  Movie({
    this.posterPath,
    this.adult,
    this.overview,
    this.releaseDate,
    this.genreIds,
    this.id,
    this.originalTitle,
    this.originalLanguage,
    this.title,
    this.backdropPath,
    this.popularity,
    this.voteCount,
    this.video,
    this.voteAverage,
  });

  Movie.fromJsonMap(Map<String, dynamic> json) {
    voteCount = json['vote_count'];
    id = json['id'];
    video = json['video'];
    voteAverage = json['vote_average'] / 1;
    title = json['title'];
    popularity = json['popularity'] / 1;
    posterPath = json['poster_path'];
    originalLanguage = json['original_language'];
    originalTitle = json['original_title'];
    genreIds = json['genre_ids'].cast<int>();
    backdropPath = json['backdrop_path'];
    adult = json['adult'];
    overview = json['overview'];
    releaseDate = json['release_date'];
  }

  getPosterImage() {
    if (posterPath == null) {
      return 'https://firebasestorage.googleapis.com/v0/b/flutter-apps-86cfe.appspot.com/o/no-image.jpg?alt=media&token=276d0ea8-891e-4e09-9cb6-1dd97e75d891';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$posterPath';
    } 
  }

  getBackdropImage() {
    if (backdropPath == null) {
      return 'https://firebasestorage.googleapis.com/v0/b/flutter-apps-86cfe.appspot.com/o/no-image.jpg?alt=media&token=276d0ea8-891e-4e09-9cb6-1dd97e75d891';
    } else {
      return 'https://image.tmdb.org/t/p/w500/$backdropPath';
    } 
  }
}
